// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Website2
{
    public partial class BlazorDiaryItemsList
    {
        public int Id { get; set; }
        public DateTime ItemDate { get; set; }
        public int ItemPeriod { get; set; }
        public int? CompanyId { get; set; }
        public string AreaTitle { get; set; }
        public string Status { get; set; }
        public string CompanyName { get; set; }
        public string Town { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Postcode { get; set; }
        public double? DiaryLat { get; set; }
        public double? DiaryLong { get; set; }
        public int StatusLevel { get; set; }
        public string Conclusion { get; set; }
        public int CoverRequired { get; set; }
        public int UserId { get; set; }
    }
}