// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Website2
{
    public partial class Company
    {
        public int Id { get; set; }
        public int ImportBatchId { get; set; }
        public string CompanyStatus { get; set; }
        public int AllowCall { get; set; }
        public int? AgentId { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string PostcodeRaw { get; set; }
        public int PostCodeId { get; set; }
        public string ContactTitle { get; set; }
        public string ContactForename { get; set; }
        public string ContactSurname { get; set; }
        public string ContactPosition { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public DateTime? HoldUntil { get; set; }
        public int? CallRescheduled { get; set; }
        public DateTime? PolicyExpires { get; set; }
        public string PolicyProvider { get; set; }
        public DateTime? LastCalled { get; set; }
        public string Notes { get; set; }
        public string Address3 { get; set; }
        public int? LocationId { get; set; }
        public int? IsStandardLifedata { get; set; }
        public string Promotion { get; set; }
        public int? CallBackMonth { get; set; }
        public int? CallBackYear { get; set; }
        public DateTime? Tpsuntil { get; set; }
        public int? Id118 { get; set; }
        public string SeniorDecisionMaker { get; set; }
        public string MainTel { get; set; }
        public string MobileTel { get; set; }
        public string Dditel { get; set; }
        public string OriginalStatus { get; set; }
        public string OriginalNumber { get; set; }
        public string Employees { get; set; }
        public string ConsentGivenBy { get; set; }
        public string ConsentGivenByPosition { get; set; }
        public DateTime? ConsentGivenByDate { get; set; }
        public DateTime? ConsentUntil { get; set; }
        public bool? ConsentRefused { get; set; }
        public string ConsentCollectedBy { get; set; }
        public int? LegalEntity { get; set; }
        public string BusinessType { get; set; }
        public string Urn { get; set; }
    }
}