// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Website2
{
    public partial class DiaryItem
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime ItemDate { get; set; }
        public int ItemPeriod { get; set; }
        public int? CompanyId { get; set; }
        public int Status { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Postcode { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public DateTime? FeedbackDate { get; set; }
        public string FeedbackStatus { get; set; }
        public string Conclusion { get; set; }
        public DateTime? ConclusionDate { get; set; }
        public DateTime? SoldDate { get; set; }
        public DateTime? PolicyStarts { get; set; }
        public double? PolicyValue { get; set; }
        public string PolicyType { get; set; }
        public DateTime? NextcallDate { get; set; }
        public DateTime? Created { get; set; }
        public int? AgentId { get; set; }
        public string Confirmed { get; set; }
        public int? FbappSat { get; set; }
        public int? FbinvolvedPmi { get; set; }
        public string Fbcontact { get; set; }
        public string Fbposition { get; set; }
        public string Fbprovider { get; set; }
        public string Fbrenewal { get; set; }
        public string Fbnote { get; set; }
        public string FboutCome { get; set; }
        public string FbReason { get; set; }
        public int? FbisSale { get; set; }
        public string Fbvalue { get; set; }
        public string FbsoldDate { get; set; }
        public string FbstartDate { get; set; }
        public string FbsaleType { get; set; }
        public int WasInsured { get; set; }
        public string FbpminextContact { get; set; }
        public string FbpreviousProvider { get; set; }
        public string FbpminotPresented { get; set; }
        public string FblifeOutCome { get; set; }
        public string FblifeNextContact { get; set; }
        public string FblifeNotPresented { get; set; }
        public string FblifeValue { get; set; }
        public string FblifeStartedDate { get; set; }
        public string FblifeSoldDate { get; set; }
        public int CoverRequired { get; set; }
        public DateTime? Cssent { get; set; }
        public string Cspunctual { get; set; }
        public string Csprofessional { get; set; }
        public string CscalledBefore { get; set; }
        public string CsquotedInMeeting { get; set; }
        public string CsquoteMethod { get; set; }
        public string CsquoteInfo { get; set; }
        public string Cscomments { get; set; }
        public int Cscompleted { get; set; }
        public DateTime? CscompletedDate { get; set; }
    }
}