// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Website2
{
    public partial class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public int UserLevelId { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public int Status { get; set; }
        public int? AreaId { get; set; }
        public int HasApp1 { get; set; }
        public int HasApp2 { get; set; }
        public int HasApp3 { get; set; }
        public int HasApp4 { get; set; }
        public int HasApp5 { get; set; }
        public DateTime? AppTime1 { get; set; }
        public DateTime? AppTime2 { get; set; }
        public DateTime? AppTime3 { get; set; }
        public DateTime? AppTime4 { get; set; }
        public DateTime? AppTime5 { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string Postcode { get; set; }
        public string Position { get; set; }
        public int? AppPerWeek { get; set; }
        public int? OkmaxDist { get; set; }
        public int? MedMaxDist { get; set; }
        public int? LongMaxDist { get; set; }
        public int? SuspendCallbacks { get; set; }
        public int OverrideDiaryWeeks { get; set; }
    }
}